var snippets = {
    "C" : "c.md",
    "CSS" : "css.md",
    "English" : "english.md",
    "HAML" : "haml.md",
    "Haskell" : "haskell.md",
    "HTML" : "html.md",
    "JavaScript" : "javascript.md",
    "JSON" : "json.md",
    "Markdown" : "markdown.md",
    "PHP" : "php.md",
    "Python" : "python.md",
    "R" : "r.md",
    "reStructuredText" : "restructuredtext.md",
    "Ruby" : "ruby.md",
    "Typescript" : "typescript.md",
    "YAML" : "yaml.md",   
}
